#!/bin/bash

root=$(git rev-parse --show-toplevel)

function collect_challenges_by_category {
    local dir=$1
    local level=$2

    while read -r subdir; do
        if [[ -f "$subdir/Package.swift" ]]; then
            echo "- [$(basename "$subdir")](${subdir/$root\//})"
            continue
        fi

        echo "$(yes '#' | head -n $level | tr -d '\n') $(basename "$subdir")"
        echo
        collect_challenges_by_category "$subdir" $((level + 1))
        echo
    done < <(find "$dir" -type d -mindepth 1 -maxdepth 1 -not -name "*.*")
}

function collect_challenges_by_difficulty {
    local dir=$1
    local difficulty=$2
    local lines=

    while read -r package; do
        subdir=$(dirname "$package")
        readme=$subdir/README.md
        if grep -q "Difficulty: $difficulty" "$readme"; then
            lines=$lines"\n- [$(basename "$subdir")](${subdir/$root\//})"
        fi
    done < <(find "$dir" -name "Package.swift")
    echo -e "${lines:-\nNone yet}" | sort
}

echo "Challenges by Category"
echo "----------------------"
echo
collect_challenges_by_category "$root" 3

echo "Challenges by Difficulty"
echo "------------------------"
echo
echo "### Easy"
collect_challenges_by_difficulty "$root" "easy"
echo
echo "### Medium"
collect_challenges_by_difficulty "$root" "medium"
echo
echo "### Hard"
collect_challenges_by_difficulty "$root" "hard"
